# Generated by Django 6.0.5 on 2026-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examauditlog',
            old_name='action',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='examauditlog',
            name='target',
        ),
        migrations.AddField(
            model_name='examauditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examauditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='examauditlog',
            name='severity',
            field=models.IntegerField(default=0),
        ),
    ]
