# Generated by Django 6.0.5 on 2026-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0006_rename_action_examauditlog_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examauditlog',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='audit_evidence/'),
        ),
    ]
