# Generated by Django 6.0.5 on 2026-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
